[
theme
]
primaryColor = "#03707d"  # Dark teal
backgroundColor = "#fbfaf8"  # Off-white
secondaryBackgroundColor = "#e8e6e4"  # Light gray
textColor = "#03707d"  # Dark teal for text
font = "sans serif"
base = "light"